language: node_js

node_js:
  - 10
  - 8

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - travis_retry npm install

script:
  - npm run test

after_success:
  - npm run codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - npm install
        script:
          - npm run semantic-release
