language: node_js

node_js:
  - 10
  - 8

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        install:
          - npm install -g codecov
          - npm install
        after_success:
          - npm run semantic-release
          - codecov
